# Generated by Django 5.2 on 2025-05-04 12:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='backups/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
