# Generated by Django 5.2 on 2025-05-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='backups/'),
        ),
    ]
