# Generated by Django 5.2 on 2025-05-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups_management', '0002_alter_backup_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup',
            options={'verbose_name': 'Backup', 'verbose_name_plural': 'Backups'},
        ),
    ]
