# Generated by Django 5.2 on 2025-05-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups_management', '0003_alter_backup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='media_archive',
            field=models.FileField(blank=True, null=True, upload_to='backups/media/'),
        ),
    ]
