# Generated by Django 5.2 on 2025-04-21 13:33

import manager.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_shareablelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=manager.models.document_upload_path, validators=[manager.models.validate_file_extension]),
        ),
    ]
