# Generated by Django 5.2 on 2025-04-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_remove_document_type_alter_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
