# Generated by Django 5.2 on 2025-05-03 09:59

import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_folder_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=500, upload_to=manager.models.document_upload_path, validators=[manager.models.validate_file_extension]),
        ),
    ]
