# Generated by Django 5.2 on 2025-05-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='path',
        ),
    ]
