# Generated by Django 5.2 on 2025-06-07 15:37

import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_remove_folder_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=manager.models.document_upload_path, validators=[manager.models.validate_file_extension]),
        ),
    ]
