# Generated by Django 5.2 on 2025-06-16 09:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_document_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='level',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('delete', 'Delete'), ('track', 'Track')], max_length=10),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('view', 'Document Viewed'), ('edit', 'Document Edited'), ('create', 'Document Created'), ('delete', 'Document Deleted'), ('download', 'Document Downloaded'), ('upload', 'Document Uploaded'), ('share', 'Document Shared'), ('permission_change', 'Permission Changed'), ('restore', 'Document Restored'), ('rename', 'Document Renamed'), ('move', 'Document Moved'), ('websocket_connect', 'Real-time Edit Connected'), ('websocket_disconnect', 'Real-time Edit Disconnected'), ('auto_save', 'Auto Save'), ('manual_save', 'Manual Save')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='manager.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['document', '-timestamp'], name='manager_act_documen_fc681a_idx'), models.Index(fields=['user', '-timestamp'], name='manager_act_user_id_472d30_idx'), models.Index(fields=['activity_type', '-timestamp'], name='manager_act_activit_2eea49_idx')],
            },
        ),
    ]
