# Generated by Django 5.2 on 2025-06-27 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_shareablelink_access_level_shareablelink_folder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareablelink',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='shareablelink',
            name='folder',
        ),
        migrations.AlterField(
            model_name='shareablelink',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='manager.document'),
        ),
    ]
